base_model = "zhipuai/glm-5.3-flash"
name = "GLM 5.3 Flash"
attachment = false

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "effort"
values = ["low", "high", "max"]

[cost]
input = 0.15
output = 0.5
cache_read = 0.07
cache_write = 0

[limit]
context = 1_048_576
output = 1_048_576

[modalities]
input = ["text"]
