base_model = "zhipuai/glm-5.3"
name = "GLM 5.3"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "effort"
values = ["low", "high", "max"]

[cost]
input = 1.0138
output = 3.2889
cache_read = 0.2453
cache_write = 0

[limit]
context = 1_048_576
output = 1_048_576
